export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",

  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",

  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_REMOVED = "ROLE_REMOVED",

  PERMISSION_GRANTED = "PERMISSION_GRANTED",
  PERMISSION_DENIED = "PERMISSION_DENIED",

  APPROVE = "APPROVE",
  REJECT = "REJECT",

  IMPORT = "IMPORT",
  EXPORT = "EXPORT",

  SYSTEM_EVENT = "SYSTEM_EVENT",
}
